runtime: python27
api_version: 1
threadsafe: yes

env_variables:
      DJANGO_SETTINGS_MODULE: 'myapp.settings'
      BIGQUERY_DATASET_ID : "babynames"
      APPLICATION_ID : "bamboo-creek-172917"
      DRC_BUCKET_NAME : "aahlad-test-aou-curation-spec-site-bucket"
      BUCKET_NAME_NYC : "aahlad-test-site-bucket-aou-data-steward-nyc"
      BUCKET_NAME_PITT : "aahlad-test-site-bucket-aou-data-steward-pitt"
      BUCKET_NAME_FAKE : "bamboo-creek-172917.appspot.com"

handlers:
- url: /h/.*
  script: change_notification_client.app

- url: /tasks/.*
  script: spec.main.app

- url: /.*
  script: validation.main.app
